#!/usr/bin/env python3
"""
gen-ia-toc.py — generate (or verify) the table of contents in docs/ia.md.

A hand-written TOC is a list the document itself already answers, so it rots the moment a heading
is renamed — the exact failure hygiene rule 2 is about. This makes it derived instead: the file is
the only source, this script writes the block, and `--check` fails when the block no longer matches
the headings. `tools/check-ia-sync.py` runs that check, so a stale TOC cannot ship quietly.

  python3 tools/gen-ia-toc.py            # rewrite the TOC block in place
  python3 tools/gen-ia-toc.py --check    # exit 1 if the block is stale (writes nothing)

Anchor slugs follow GitHub's algorithm: downcase, drop every character that is not a word
character / hyphen / space, then spaces to hyphens. Duplicates take -1, -2 … in document order.
Verified against the real thing via `gh api --method POST /markdown` — see the test in the commit
that added this file; do not "simplify" the slug rule without re-running that comparison.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IA = ROOT / "docs" / "ia.md"

START = "<!-- TOC:START — generated by tools/gen-ia-toc.py; do not edit by hand -->"
END = "<!-- TOC:END -->"
TOC_HEADING = "## Contents"


def slug(text, seen):
    s = text.lower()
    s = re.sub(r"[^\w\- ]", "", s, flags=re.UNICODE)
    s = s.replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def headings(src):
    """(level, raw text) for every H1-H3 outside fenced code, in document order.

    The H1 and the TOC's own heading are RETURNED even though the TOC does not list them: the
    renderer numbers duplicate slugs across all headings, so skipping one here would shift every
    anchor after it. build() decides what to print; this decides what counts."""
    out, in_fence = [], False
    for line in src.split("\n"):
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{1,3}) +(.*?)\s*$", line)
        if m:
            out.append((len(m.group(1)), m.group(2)))
    return out


def build(src):
    seen, lines = {}, []
    for level, raw in headings(src):
        anchor = slug(raw, seen)  # consumed for every heading, printed for some
        if level == 1 or f"{'#' * level} {raw}" == TOC_HEADING:
            continue
        label = raw.replace("**", "").strip()
        indent = "" if level == 2 else "  "
        lines.append(f"{indent}- [{label}](#{anchor})")
    return "\n".join(lines)


def main():
    src = IA.read_text(encoding="utf-8")
    body = build(src)
    block = f"{TOC_HEADING}\n\n{START}\n\n{body}\n\n{END}"

    existing = re.search(
        re.escape(TOC_HEADING) + r"\n\n" + re.escape(START) + r".*?" + re.escape(END), src, re.S
    )

    if "--check" in sys.argv:
        if not existing:
            print("FAIL  docs/ia.md has no generated TOC block — run: python3 tools/gen-ia-toc.py")
            return 1
        if existing.group(0) != block:
            print("FAIL  docs/ia.md TOC is stale — run: python3 tools/gen-ia-toc.py")
            return 1
        print(f"OK    TOC current ({body.count(chr(10)) + 1} entries)")
        return 0

    if existing:
        src = src[: existing.start()] + block + src[existing.end() :]
    else:
        # First run: place it after the header block's --- separator, before the first ## section.
        m = re.search(r"\n---\n\n(?=## )", src)
        if not m:
            print("FAIL  could not find the header separator to insert the TOC after")
            return 1
        src = src[: m.end()] + block + "\n\n---\n\n" + src[m.end() :]

    IA.write_text(src, encoding="utf-8")
    print(f"wrote TOC: {body.count(chr(10)) + 1} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
